const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';
const brandPurple = '#b3a0ff';
const orange = '#ffbe59';
export default {
  light: {
    text: '#0d101b',
    background: '#f8f8f8',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    brandPurple: brandPurple,
    orange: orange,
    cardBackground: '#fff',
    border: '#F0F0F0',
    iconBackground: '#F5F7FA',
    textSecondary: '#666',
    destructive: '#FF3B30',
    shadow: '#000',
    menuPressed: '#F9FAFB',
    keypadBackground: '#fff',
    keypadText: '#0d101b',
    keypadPressed: '#eef2ff',
    otpBoxBackground: '#f8f8f8',
    otpBoxBorder: 'rgba(13,16,27,0.12)',
    destructiveBackground: '#fdecea',
    destructiveBorder: 'rgba(229,57,53,0.2)',
  },
  dark: {
    text: '#f8f8f8',
    background: '#0d101b',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    brandPurple: '#5b4cb5', // Darker purple for dark mode contrast
    cardBackground: '#1c1c1e',
    border: '#2c2c2e',
    iconBackground: '#2c2c2e',
    textSecondary: '#8E8E93',
    destructive: '#FF453A',
    shadow: '#000',
    menuPressed: '#2c2c2e',
    orange: orange,
    keypadBackground: '#1c1c1e',
    keypadText: '#fff',
    keypadPressed: '#2c2c2e',
    otpBoxBackground: '#2c2c2e',
    otpBoxBorder: '#3a3a3c',
    destructiveBackground: '#3a1c1c',
    destructiveBorder: 'rgba(255,69,58,0.3)',
  },
};
